from __future__ import annotations

from collections.abc import Iterable, Sequence
from enum import Enum
from os import PathLike
from typing import overload


class MatrixErr(Enum):
    SizeTooLarge: MatrixErr
    AllocationFailed: MatrixErr
    DimensionMismatch: MatrixErr


class MatrixError(RuntimeError): ...

class RuntimeFeatures:
    avx2_compiled: bool
    avx2_available: bool
    parallel_compiled: bool
    parallel_enabled: bool
    max_threads: int
    bit_ops_backend: str
    fwht_backend: str

    def __init__(self) -> None: ...

class BitMatrix:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, rows: int, cols: int) -> None: ...

    @property
    def rows(self) -> int: ...

    @property
    def cols(self) -> int: ...

    @property
    def shape(self) -> tuple[int, int]: ...

    @property
    def stride_words(self) -> int: ...

    @property
    def words_per_row(self) -> int: ...

    @property
    def total_words(self) -> int: ...

    @property
    def total_bytes(self) -> int: ...

    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...

    def get(self, row: int, col: int) -> bool: ...
    def set(self, row: int, col: int, value: bool) -> None: ...
    def copy_from_words(self, words: Sequence[int]) -> None: ...
    def row_xor(self, target_row: int, source_row: int) -> None: ...
    def row_xor_from(self, target_row: int, source: BitMatrix, source_row: int) -> None: ...
    def add(self, other: BitMatrix) -> BitMatrix: ...
    def mul(self, other: BitMatrix) -> BitMatrix: ...
    def __matmul__(self, other: BitMatrix) -> BitMatrix: ...
    def power(self, exp: int) -> BitMatrix: ...
    def row_popcount(self, row: int) -> int: ...
    def weight(self) -> int: ...
    def swap_rows(self, r1: int, r2: int) -> None: ...
    def rank(self) -> int: ...
    def extract_rows_by_indices(self, indices: Sequence[int]) -> BitMatrix: ...
    def insert_rows_by_indices(self, source: BitMatrix, indices: Sequence[int]) -> None: ...
    def to_rows(self) -> list[str]: ...
    def to_text(self) -> str: ...
    def save_text_file(self, path: str | PathLike[str]) -> None: ...
    def save_binary_file(self, path: str | PathLike[str]) -> None: ...

    @staticmethod
    def from_rows(rows: Sequence[str]) -> BitMatrix: ...
    @staticmethod
    def from_text(text: str) -> BitMatrix: ...
    @staticmethod
    def load_text_file(path: str | PathLike[str]) -> BitMatrix: ...
    @staticmethod
    def load_binary_file(path: str | PathLike[str]) -> BitMatrix: ...
    @staticmethod
    def identity(n: int) -> BitMatrix: ...


class ApplyResult:
    applied_count: int
    weight_improvement: int

    def __init__(self) -> None: ...


class Candidate:
    mask: list[int]
    weight: int

    def __init__(self) -> None: ...
    def __init__(self, mask: Sequence[int], weight: int) -> None: ...
    def __repr__(self) -> str: ...
    def has_row(self, row: int) -> bool: ...
    def mask_popcount(self) -> int: ...
    def mask_u64(self) -> int: ...
    def selected_rows(self) -> list[int]: ...

    @staticmethod
    def from_u64(mask: int, weight: int) -> Candidate: ...
    @staticmethod
    def from_words(mask: Sequence[int], weight: int) -> Candidate: ...


class FwhtSearchConfig:
    max_rows: int
    k: int

    def __init__(self) -> None: ...


class MitmFwhtSearchConfig:
    initial_capacity_cols: int
    max_t_left: int
    max_n_right: int
    k_limit: int

    def __init__(self) -> None: ...


class FwhtSearch:
    def __init__(self, config: FwhtSearchConfig = ...) -> None: ...
    def name(self) -> str: ...
    def describe(self, window_size: int) -> str: ...
    def search(self, matrix: BitMatrix, window_rows: Sequence[int]) -> list[Candidate]: ...


class MitmFwhtSearch:
    def __init__(self, config: MitmFwhtSearchConfig = ...) -> None: ...
    def name(self) -> str: ...
    def describe(self, window_size: int) -> str: ...
    def search(self, matrix: BitMatrix, window_rows: Sequence[int]) -> list[Candidate]: ...


class GreedySelection:
    def __init__(self, min_gain: int, stochastic: bool = False, seed: int = 0) -> None: ...
    def apply(
        self,
        matrix: BitMatrix,
        window_rows: Sequence[int],
        candidates: Sequence[Candidate],
    ) -> ApplyResult: ...


def get_version() -> str: ...
def add(a: int, b: int) -> int: ...
def fixed_weight_masks_u32(n: int, k: int) -> list[int]: ...
def fixed_weight_masks_u64(n: int, k: int) -> list[int]: ...
def fwht_i16(data: Sequence[int]) -> list[int]: ...
def fwht_i32(data: Sequence[int]) -> list[int]: ...

def matrix_from_rows(rows: Sequence[str]) -> BitMatrix: ...

def make_fwht_config(*, max_rows: int = 16, k: int = 64) -> FwhtSearchConfig: ...

def make_mitm_fwht_config(
    *,
    initial_capacity_cols: int = 1024,
    max_t_left: int = 20,
    max_n_right: int = 1 << 16,
    k_limit: int = 64,
) -> MitmFwhtSearchConfig: ...

def fwht_search(
    matrix: BitMatrix,
    window_rows: Iterable[int],
    *,
    max_rows: int = 16,
    k: int = 64,
) -> list[Candidate]: ...

def mitm_fwht_search(
    matrix: BitMatrix,
    window_rows: Iterable[int],
    *,
    initial_capacity_cols: int = 1024,
    max_t_left: int = 20,
    max_n_right: int = 1 << 16,
    k_limit: int = 64,
) -> list[Candidate]: ...

def apply_greedy(
    matrix: BitMatrix,
    window_rows: Iterable[int],
    candidates: Iterable[Candidate],
    *,
    min_gain: int,
    stochastic: bool = False,
    seed: int = 0,
) -> ApplyResult: ...

def get_runtime_features() -> RuntimeFeatures: ...

__version__: str

__all__: list[str]