"""
Low-level nanobind bindings for bmmpy.

This module exposes the native core types and algorithms used by the public bmmpy package. Most users should import from bmmpy instead of bmmpy._bmmpy.
"""

from collections.abc import Iterator, Sequence
import enum
import os
from typing import overload


class RowWindow:
    def __len__(self) -> int: ...

    def __repr__(self) -> str: ...

    @property
    def size(self) -> int: ...

    @property
    def cols(self) -> int: ...

    @property
    def shape(self) -> tuple: ...

    @property
    def rows(self) -> list[int]: ...

    def row_popcount(self, local_row: int) -> int: ...

    @property
    def total_weight(self) -> int: ...

    def assign_materialized(self, rows: BitMatrix) -> None: ...

    def materialize(self) -> BitMatrix: ...

class MatrixError(RuntimeError):
    pass

class MatrixErr(enum.Enum):
    SizeTooLarge = 0

    AllocationFailed = 1

    DimensionMismatch = 2

class BitMatrix:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, rows: int, cols: int) -> None: ...

    @property
    def rows(self) -> int: ...

    @property
    def cols(self) -> int: ...

    @property
    def shape(self) -> tuple: ...

    @property
    def stride_words(self) -> int: ...

    @property
    def words_per_row(self) -> int: ...

    @property
    def total_words(self) -> int: ...

    @property
    def total_bytes(self) -> int: ...

    def __len__(self) -> int: ...

    def __str__(self) -> str: ...

    def __repr__(self) -> str: ...

    def copy(self) -> BitMatrix: ...

    def __getitem__(self, index: tuple) -> bool: ...

    def __setitem__(self, index: tuple, value: bool) -> None: ...

    def get(self, row: int, col: int) -> bool: ...

    def set(self, row: int, col: int, value: bool) -> None: ...

    def copy_from_words(self, words: Sequence[int]) -> None: ...

    def row_xor(self, target_row: int, source_row: int) -> None: ...

    def row_xor_from(self, target_row: int, source: BitMatrix, source_row: int) -> None: ...

    def add(self, other: BitMatrix) -> BitMatrix: ...

    def mul(self, other: BitMatrix) -> BitMatrix: ...

    def __matmul__(self, other: BitMatrix) -> BitMatrix: ...

    def power(self, exp: int) -> BitMatrix: ...

    def row_popcount(self, row: int) -> int: ...

    def weight(self) -> int: ...

    def swap_rows(self, r1: int, r2: int) -> None: ...

    def rank(self) -> int: ...

    def extract_rows_by_indices(self, indices: Sequence[int]) -> BitMatrix: ...

    def row_window(self, rows: Sequence[int]) -> RowWindow: ...

    def insert_rows_by_indices(self, source: BitMatrix, indices: Sequence[int]) -> None: ...

    def to_rows(self) -> list[str]: ...

    def to_text(self) -> str: ...

    def save_text_file(self, path: str | os.PathLike) -> None: ...

    def save_binary_file(self, path: str | os.PathLike) -> None: ...

    def hash(self) -> str: ...

    @staticmethod
    def from_rows(rows: Sequence[str]) -> BitMatrix: ...

    @staticmethod
    def from_text(text: str) -> BitMatrix: ...

    @staticmethod
    def load_text_file(path: str | os.PathLike) -> BitMatrix: ...

    @staticmethod
    def load_binary_file(path: str | os.PathLike) -> BitMatrix: ...

    @staticmethod
    def identity(n: int) -> BitMatrix: ...

class RowTransformError(ValueError):
    pass

class BitVector:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, bit_count: int) -> None: ...

    @property
    def bit_count(self) -> int: ...

    @property
    def word_count(self) -> int: ...

    def __len__(self) -> int: ...

    def any(self) -> bool: ...

    def none(self) -> bool: ...

    def get(self, bit_index: int) -> bool: ...

    def set(self, bit_index: int, value: bool = True) -> None: ...

    def flip(self, bit_index: int) -> None: ...

    def to_words(self) -> list[int]: ...

    @staticmethod
    def from_u64(value: int, bit_count: int = 0) -> BitVector: ...

    @staticmethod
    def from_words(bit_count: int, words: Sequence[int]) -> BitVector: ...

    @staticmethod
    def from_positions(bit_count: int, positions: Sequence[int]) -> BitVector: ...

def find_row_transform(source: BitMatrix, target: BitMatrix) -> BitMatrix: ...

def invert_matrix(matrix: BitMatrix) -> BitMatrix: ...

def powers_to_field_element(powers: Sequence[int], degree: int, poly_powers: Sequence[int]) -> BitVector: ...

def build_basis_change_matrix(basis_elements: Sequence[BitVector], degree: int) -> BitMatrix: ...

def basis_mask_to_field_element(mask: BitVector, basis_elements: Sequence[BitVector], degree: int) -> BitVector: ...

def field_element_to_basis_mask(element_bits: BitVector, change_inv: BitMatrix) -> BitVector: ...

class MastrovitoCore:
    def __init__(self, degree: int, powers: Sequence[int], element_standard_bits: BitVector, basis_elements: Sequence[BitVector] = []) -> None: ...

    @property
    def degree(self) -> int: ...

    @property
    def powers(self) -> list[int]: ...

    def get_basis_multiplication_matrices(self) -> list[BitMatrix]: ...

    def get_mastrovito_matrix(self, power_bits: BitVector) -> BitMatrix: ...

    def build_check_matrix(self, c: int, k: int, start_bits: BitVector) -> BitMatrix: ...

class Candidate:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, mask: Sequence[int], weight: int) -> None: ...

    def __len__(self) -> int: ...

    @property
    def mask(self) -> list[int]: ...

    @mask.setter
    def mask(self, arg: Sequence[int], /) -> None: ...

    @property
    def weight(self) -> int: ...

    @weight.setter
    def weight(self, arg: int, /) -> None: ...

    def __repr__(self) -> str: ...

    def __contains__(self, row: int) -> bool: ...

    def __iter__(self) -> Iterator[int]: ...

    def has_row(self, row: int) -> bool: ...

    @property
    def rows(self) -> list[int]: ...

    def mask_popcount(self) -> int: ...

    def mask_u64(self) -> int: ...

    def selected_rows(self) -> list[int]: ...

    @staticmethod
    def from_u64(mask: int, weight: int) -> Candidate: ...

    @staticmethod
    def from_words(mask: Sequence[int], weight: int) -> Candidate: ...

class BruteforceSearchConfig:
    def __init__(self) -> None: ...

    @property
    def max_candidates(self) -> int: ...

    @max_candidates.setter
    def max_candidates(self, arg: int, /) -> None: ...

    @property
    def chunk_bits(self) -> int: ...

    @chunk_bits.setter
    def chunk_bits(self, arg: int, /) -> None: ...

class FwhtSearchConfig:
    def __init__(self) -> None: ...

    @property
    def max_rows(self) -> int: ...

    @max_rows.setter
    def max_rows(self, arg: int, /) -> None: ...

    @property
    def max_candidates(self) -> int: ...

    @max_candidates.setter
    def max_candidates(self, arg: int, /) -> None: ...

class MitmFwhtSearchConfig:
    def __init__(self) -> None: ...

    @property
    def reserve_unique_patterns(self) -> int: ...

    @reserve_unique_patterns.setter
    def reserve_unique_patterns(self, arg: int, /) -> None: ...

    @property
    def reserve_left_rows(self) -> int: ...

    @reserve_left_rows.setter
    def reserve_left_rows(self, arg: int, /) -> None: ...

    @property
    def reserve_right_states(self) -> int: ...

    @reserve_right_states.setter
    def reserve_right_states(self, arg: int, /) -> None: ...

    @property
    def max_candidates(self) -> int: ...

    @max_candidates.setter
    def max_candidates(self, arg: int, /) -> None: ...

class CudaMitmFwhtSearchConfig:
    def __init__(self) -> None: ...

    @property
    def max_candidates(self) -> int: ...

    @max_candidates.setter
    def max_candidates(self, arg: int, /) -> None: ...

    @property
    def low_bits(self) -> int: ...

    @low_bits.setter
    def low_bits(self, arg: int, /) -> None: ...

class BruteforceSearch:
    def __init__(self, config: BruteforceSearchConfig = ...) -> None: ...

    def name(self) -> str: ...

    def search(self, window: RowWindow) -> list[Candidate]: ...

class FwhtSearch:
    def __init__(self, config: FwhtSearchConfig = ...) -> None: ...

    def name(self) -> str: ...

    def search(self, window: RowWindow) -> list[Candidate]: ...

class MitmFwhtSearch:
    def __init__(self, config: MitmFwhtSearchConfig = ...) -> None: ...

    def name(self) -> str: ...

    def search(self, window: RowWindow) -> list[Candidate]: ...

class CudaMitmFwhtSearch:
    def __init__(self, config: CudaMitmFwhtSearchConfig = ...) -> None: ...

    def name(self) -> str: ...

    def search(self, window: RowWindow) -> list[Candidate]: ...

class CudaBruteforceSearchConfig:
    def __init__(self) -> None: ...

    @property
    def max_candidates(self) -> int: ...

    @max_candidates.setter
    def max_candidates(self, arg: int, /) -> None: ...

    @property
    def chunk_bits(self) -> int: ...

    @chunk_bits.setter
    def chunk_bits(self, arg: int, /) -> None: ...

class CudaBruteforceSearch:
    def __init__(self, config: CudaBruteforceSearchConfig = ...) -> None: ...

    def name(self) -> str: ...

    def search(self, window: RowWindow) -> list[Candidate]: ...

class WindowScorePolicyKind(enum.Enum):
    PairwiseSynergy = 0

    HigherOrderSynergy = 1

class CoolingPolicyKind(enum.Enum):
    AdaptiveGeometric = 0

class SASelectorConfig:
    def __init__(self) -> None: ...

    @property
    def iterations(self) -> int: ...

    @iterations.setter
    def iterations(self, arg: int, /) -> None: ...

    @property
    def restarts(self) -> int: ...

    @restarts.setter
    def restarts(self, arg: int, /) -> None: ...

    @property
    def seed(self) -> int: ...

    @seed.setter
    def seed(self, arg: int, /) -> None: ...

    @property
    def score_policy(self) -> WindowScorePolicyKind: ...

    @score_policy.setter
    def score_policy(self, arg: WindowScorePolicyKind, /) -> None: ...

    @property
    def cooling_policy(self) -> CoolingPolicyKind: ...

    @cooling_policy.setter
    def cooling_policy(self, arg: CoolingPolicyKind, /) -> None: ...

    @property
    def temperature_probe_samples(self) -> int: ...

    @temperature_probe_samples.setter
    def temperature_probe_samples(self, arg: int, /) -> None: ...

    @property
    def initial_acceptance_probability(self) -> float: ...

    @initial_acceptance_probability.setter
    def initial_acceptance_probability(self, arg: float, /) -> None: ...

    @property
    def cooling_rate(self) -> float: ...

    @cooling_rate.setter
    def cooling_rate(self, arg: float, /) -> None: ...

    @property
    def min_temperature(self) -> float: ...

    @min_temperature.setter
    def min_temperature(self, arg: float, /) -> None: ...

class SASelectionResult:
    def __init__(self) -> None: ...

    @property
    def rows(self) -> list[int]: ...

    @rows.setter
    def rows(self, arg: Sequence[int], /) -> None: ...

    @property
    def score(self) -> int: ...

    @score.setter
    def score(self, arg: int, /) -> None: ...

    @property
    def accepted_moves(self) -> int: ...

    @accepted_moves.setter
    def accepted_moves(self, arg: int, /) -> None: ...

    @property
    def iterations_run(self) -> int: ...

    @iterations_run.setter
    def iterations_run(self, arg: int, /) -> None: ...

    @property
    def best_iteration(self) -> int: ...

    @best_iteration.setter
    def best_iteration(self, arg: int, /) -> None: ...

    @property
    def restart_index(self) -> int: ...

    @restart_index.setter
    def restart_index(self, arg: int, /) -> None: ...

    @property
    def seed(self) -> int: ...

    @seed.setter
    def seed(self, arg: int, /) -> None: ...

class SASelector:
    def __init__(self, config: SASelectorConfig = ...) -> None: ...

    def name(self) -> str: ...

    def select(self, matrix: BitMatrix, window_size: int) -> SASelectionResult: ...

    def select_window(self, matrix: BitMatrix, window_size: int) -> RowWindow: ...

class ApplyResult:
    def __init__(self) -> None: ...

    @property
    def applied_count(self) -> int: ...

    @applied_count.setter
    def applied_count(self, arg: int, /) -> None: ...

    @property
    def weight_improvement(self) -> int: ...

    @weight_improvement.setter
    def weight_improvement(self, arg: int, /) -> None: ...

class GreedyApplier:
    def __init__(self, min_gain: int, stochastic: bool = False, seed: int = 0) -> None: ...

    def apply(self, window: RowWindow, candidates: Sequence[Candidate]) -> ApplyResult: ...

class GlobalGreedyApplier:
    def __init__(self, require_improvement: bool = True) -> None: ...

    def name(self) -> str: ...

    def apply(self, window: RowWindow, candidates: Sequence[Candidate]) -> ApplyResult: ...

class RuntimeFeatures:
    def __init__(self) -> None: ...

    @property
    def avx2_compiled(self) -> bool: ...

    @avx2_compiled.setter
    def avx2_compiled(self, arg: bool, /) -> None: ...

    @property
    def avx2_available(self) -> bool: ...

    @avx2_available.setter
    def avx2_available(self, arg: bool, /) -> None: ...

    @property
    def cuda_compiled(self) -> bool: ...

    @cuda_compiled.setter
    def cuda_compiled(self, arg: bool, /) -> None: ...

    @property
    def cuda_available(self) -> bool: ...

    @cuda_available.setter
    def cuda_available(self, arg: bool, /) -> None: ...

    @property
    def parallel_compiled(self) -> bool: ...

    @parallel_compiled.setter
    def parallel_compiled(self, arg: bool, /) -> None: ...

    @property
    def parallel_enabled(self) -> bool: ...

    @parallel_enabled.setter
    def parallel_enabled(self, arg: bool, /) -> None: ...

    @property
    def max_threads(self) -> int: ...

    @max_threads.setter
    def max_threads(self, arg: int, /) -> None: ...

    @property
    def bit_ops_backend(self) -> str: ...

    @bit_ops_backend.setter
    def bit_ops_backend(self, arg: str, /) -> None: ...

    @property
    def fwht_backend(self) -> str: ...

    @fwht_backend.setter
    def fwht_backend(self, arg: str, /) -> None: ...

    def __repr__(self) -> str: ...

def get_version() -> str:
    """Get the version of the library"""

def add(a: int, b: int) -> int:
    """Add two integers"""

def get_runtime_features() -> RuntimeFeatures:
    """Return runtime feature flags for this build and host"""

def fixed_weight_masks_u32(n: int, k: int) -> list[int]: ...

def fixed_weight_masks_u64(n: int, k: int) -> list[int]: ...

def fwht_i16(data: Sequence[int]) -> list[int]: ...

def fwht_i32(data: Sequence[int]) -> list[int]: ...

class ExactBasisSolverConfig:
    def __init__(self) -> None: ...

    @property
    def max_rows(self) -> int: ...

    @max_rows.setter
    def max_rows(self, arg: int, /) -> None: ...

    @property
    def max_states(self) -> int: ...

    @max_states.setter
    def max_states(self, arg: int, /) -> None: ...

    @property
    def max_storage_bytes(self) -> int: ...

    @max_storage_bytes.setter
    def max_storage_bytes(self, arg: int, /) -> None: ...

class ExactBasisResult:
    def __init__(self) -> None: ...

    @property
    def input_rows(self) -> int: ...

    @input_rows.setter
    def input_rows(self, arg: int, /) -> None: ...

    @property
    def cols(self) -> int: ...

    @cols.setter
    def cols(self, arg: int, /) -> None: ...

    @property
    def rank(self) -> int: ...

    @rank.setter
    def rank(self, arg: int, /) -> None: ...

    @property
    def enumerated_states(self) -> int: ...

    @enumerated_states.setter
    def enumerated_states(self, arg: int, /) -> None: ...

    @property
    def total_weight(self) -> int: ...

    @total_weight.setter
    def total_weight(self, arg: int, /) -> None: ...

    @property
    def basis_masks(self) -> list[int]: ...

    @basis_masks.setter
    def basis_masks(self, arg: Sequence[int], /) -> None: ...

    @property
    def basis_weights(self) -> list[int]: ...

    @basis_weights.setter
    def basis_weights(self, arg: Sequence[int], /) -> None: ...

    @property
    def transform_matrix(self) -> BitMatrix: ...

    @transform_matrix.setter
    def transform_matrix(self, arg: BitMatrix, /) -> None: ...

    @property
    def basis_matrix(self) -> BitMatrix: ...

    @basis_matrix.setter
    def basis_matrix(self, arg: BitMatrix, /) -> None: ...

class ExactBasisSolver:
    def __init__(self, config: ExactBasisSolverConfig = ...) -> None: ...

    def name(self) -> str: ...

    def solve(self, window: RowWindow) -> ExactBasisResult: ...
