"""
Low-level nanobind bindings for bmmpy.

This module exposes the native core types and algorithms used by the public bmmpy package. Most users should import from bmmpy instead of bmmpy._bmmpy.
"""

from collections.abc import Iterator, Sequence
import enum
import os
from typing import overload


class RowWindow:
    def __len__(self) -> int: ...

    def __repr__(self) -> str: ...

    @property
    def size(self) -> int: ...

    @property
    def cols(self) -> int: ...

    @property
    def shape(self) -> tuple: ...

    @property
    def rows(self) -> list[int]: ...

    def materialize(self) -> BitMatrix: ...

class MatrixError(RuntimeError):
    pass

class MatrixErr(enum.Enum):
    SizeTooLarge = 0

    AllocationFailed = 1

    DimensionMismatch = 2

class BitMatrix:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, rows: int, cols: int) -> None: ...

    @property
    def rows(self) -> int: ...

    @property
    def cols(self) -> int: ...

    @property
    def shape(self) -> tuple: ...

    @property
    def stride_words(self) -> int: ...

    @property
    def words_per_row(self) -> int: ...

    @property
    def total_words(self) -> int: ...

    @property
    def total_bytes(self) -> int: ...

    def __len__(self) -> int: ...

    def __str__(self) -> str: ...

    def __repr__(self) -> str: ...

    def copy(self) -> BitMatrix: ...

    def __getitem__(self, index: tuple) -> bool: ...

    def __setitem__(self, index: tuple, value: bool) -> None: ...

    def get(self, row: int, col: int) -> bool: ...

    def set(self, row: int, col: int, value: bool) -> None: ...

    def copy_from_words(self, words: Sequence[int]) -> None: ...

    def row_xor(self, target_row: int, source_row: int) -> None: ...

    def row_xor_from(self, target_row: int, source: BitMatrix, source_row: int) -> None: ...

    def add(self, other: BitMatrix) -> BitMatrix: ...

    def mul(self, other: BitMatrix) -> BitMatrix: ...

    def __matmul__(self, other: BitMatrix) -> BitMatrix: ...

    def power(self, exp: int) -> BitMatrix: ...

    def row_popcount(self, row: int) -> int: ...

    def weight(self) -> int: ...

    def swap_rows(self, r1: int, r2: int) -> None: ...

    def rank(self) -> int: ...

    def extract_rows_by_indices(self, indices: Sequence[int]) -> BitMatrix: ...

    def row_window(self, rows: Sequence[int]) -> RowWindow: ...

    def insert_rows_by_indices(self, source: BitMatrix, indices: Sequence[int]) -> None: ...

    def to_rows(self) -> list[str]: ...

    def to_text(self) -> str: ...

    def save_text_file(self, path: str | os.PathLike) -> None: ...

    def save_binary_file(self, path: str | os.PathLike) -> None: ...

    @staticmethod
    def from_rows(rows: Sequence[str]) -> BitMatrix: ...

    @staticmethod
    def from_text(text: str) -> BitMatrix: ...

    @staticmethod
    def load_text_file(path: str | os.PathLike) -> BitMatrix: ...

    @staticmethod
    def load_binary_file(path: str | os.PathLike) -> BitMatrix: ...

    @staticmethod
    def identity(n: int) -> BitMatrix: ...

class Candidate:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, mask: Sequence[int], weight: int) -> None: ...

    def __len__(self) -> int: ...

    @property
    def mask(self) -> list[int]: ...

    @mask.setter
    def mask(self, arg: Sequence[int], /) -> None: ...

    @property
    def weight(self) -> int: ...

    @weight.setter
    def weight(self, arg: int, /) -> None: ...

    def __repr__(self) -> str: ...

    def __contains__(self, row: int) -> bool: ...

    def __iter__(self) -> Iterator[int]: ...

    def has_row(self, row: int) -> bool: ...

    @property
    def rows(self) -> list[int]: ...

    def mask_popcount(self) -> int: ...

    def mask_u64(self) -> int: ...

    def selected_rows(self) -> list[int]: ...

    @staticmethod
    def from_u64(mask: int, weight: int) -> Candidate: ...

    @staticmethod
    def from_words(mask: Sequence[int], weight: int) -> Candidate: ...

class FwhtSearchConfig:
    def __init__(self) -> None: ...

    @property
    def max_rows(self) -> int: ...

    @max_rows.setter
    def max_rows(self, arg: int, /) -> None: ...

    @property
    def k(self) -> int: ...

    @k.setter
    def k(self, arg: int, /) -> None: ...

class MitmFwhtSearchConfig:
    def __init__(self) -> None: ...

    @property
    def initial_capacity_cols(self) -> int: ...

    @initial_capacity_cols.setter
    def initial_capacity_cols(self, arg: int, /) -> None: ...

    @property
    def max_t_left(self) -> int: ...

    @max_t_left.setter
    def max_t_left(self, arg: int, /) -> None: ...

    @property
    def max_n_right(self) -> int: ...

    @max_n_right.setter
    def max_n_right(self, arg: int, /) -> None: ...

    @property
    def k(self) -> int: ...

    @k.setter
    def k(self, arg: int, /) -> None: ...

class FwhtSearch:
    def __init__(self, config: FwhtSearchConfig = ...) -> None: ...

    def name(self) -> str: ...

    def describe(self, window_size: int) -> str: ...

    def search(self, window: RowWindow) -> list[Candidate]: ...

class MitmFwhtSearch:
    def __init__(self, config: MitmFwhtSearchConfig = ...) -> None: ...

    def name(self) -> str: ...

    def describe(self, window_size: int) -> str: ...

    def search(self, window: RowWindow) -> list[Candidate]: ...

class ApplyResult:
    def __init__(self) -> None: ...

    @property
    def applied_count(self) -> int: ...

    @applied_count.setter
    def applied_count(self, arg: int, /) -> None: ...

    @property
    def weight_improvement(self) -> int: ...

    @weight_improvement.setter
    def weight_improvement(self, arg: int, /) -> None: ...

class GreedySelection:
    def __init__(self, min_gain: int, stochastic: bool = False, seed: int = 0) -> None: ...

    def apply(self, window: RowWindow, candidates: Sequence[Candidate]) -> ApplyResult: ...

class RuntimeFeatures:
    def __init__(self) -> None: ...

    @property
    def avx2_compiled(self) -> bool: ...

    @avx2_compiled.setter
    def avx2_compiled(self, arg: bool, /) -> None: ...

    @property
    def avx2_available(self) -> bool: ...

    @avx2_available.setter
    def avx2_available(self, arg: bool, /) -> None: ...

    @property
    def parallel_compiled(self) -> bool: ...

    @parallel_compiled.setter
    def parallel_compiled(self, arg: bool, /) -> None: ...

    @property
    def parallel_enabled(self) -> bool: ...

    @parallel_enabled.setter
    def parallel_enabled(self, arg: bool, /) -> None: ...

    @property
    def max_threads(self) -> int: ...

    @max_threads.setter
    def max_threads(self, arg: int, /) -> None: ...

    @property
    def bit_ops_backend(self) -> str: ...

    @bit_ops_backend.setter
    def bit_ops_backend(self, arg: str, /) -> None: ...

    @property
    def fwht_backend(self) -> str: ...

    @fwht_backend.setter
    def fwht_backend(self, arg: str, /) -> None: ...

    def __repr__(self) -> str: ...

def get_version() -> str:
    """Get the version of the library"""

def add(a: int, b: int) -> int:
    """Add two integers"""

def get_runtime_features() -> RuntimeFeatures:
    """Return runtime feature flags for this build and host"""

def fixed_weight_masks_u32(n: int, k: int) -> list[int]: ...

def fixed_weight_masks_u64(n: int, k: int) -> list[int]: ...

def fwht_i16(data: Sequence[int]) -> list[int]: ...

def fwht_i32(data: Sequence[int]) -> list[int]: ...
